### Creating NumPy arrays
1. using np.array

In [1]:
import numpy as np

a1 = np.array([1, 2, 3])    # 1D array
a2 = np.array([[1, 2], [3, 4]]) # 2D array
a3 = np.array([[[1, 2], [3, 4]],    # 3D array
               [[5, 6], [7, 8]]])

print(a1)
print(a2)
print(a3)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


2. Using Numpy Function

In [2]:
import numpy as np

a0 = np.zeros((3, 3))
a1  = np.ones((2, 2))
ar  = np.arange(0, 10, 2)

print(a0)
print(a1)
print(ar)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]


#### 3. Using Numpy fromiter

In [ ]:
import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype = 'U2') # U2 means Unicode string of length 2

print("fromiter() array :",arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


#### 4. using np.arange

In [16]:
import numpy as np

np.arange(1, 20 , 2, dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

#### 5. using linspace()

In [4]:
import numpy as np

# np.linspace(3.5, 10, 3) generates 3 evenly spaced values between 3.5 and 10 → [3.5, 6.75, 10.0].
# dtype=np.int32 casts them to 32-bit integers, truncating decimals → [3, 6, 10].
arr = np.linspace(3.5, 10, 3, dtype=np.int32)

print(arr)

[ 3  6 10]


#### 6. using np.empty()

In [13]:
import numpy as np

# np.empty([4, 3], dtype=np.int32, order='f')
# - Creates a 4x3 array of type int32.
# - 'empty' means the array is allocated but not initialized, so it contains arbitrary values.
# - order='f' specifies Fortran-style (column-major) memory layout instead of the default C-style (row-major).
# - The contents will look random because they are just whatever happens to be in memory.
arr = np.empty([4, 3], dtype=np.int32, order='f')

print(arr)

[[4128860 6619251 7209077]
 [6029375 7536754 4259932]
 [3801155 7602268 7340144]
 [5570652 7471201 6357060]]


### Numpy Array Indexing

In [3]:
import numpy as np

a1 = np.array([10, 20, 30, 40, 50])
print(a1[2])      # single element
print(a1[-1])     # last element

a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])
print(a2[1, 0])   # row 1, column 0

30
50
4


### Slicing

In [5]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

print(a[1:4])    # rows 1 to 3 (4 is exclusive)
print(a[:, 1])     # all rows, column 1

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 2  5  8 11]


In [1]:
import numpy as np
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr_2d[1, 2])  

print(arr_2d[0:2, 1:3])

6
[[2 3]
 [5 6]]


## Advanced Indexing

In [7]:
import numpy as np

a = np.array([10, 20, 30, 40, 50, 60])
idx = np.array([1, 3, 5])

print(a[idx])       # integer indexing

cond = a > 30
print(a[cond])      # boolean indexing , returns elements greater than 30

[20 40 60]
[40 50 60]


#### Basic Arithmetic Operations

In [ ]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])


print(x + y)    # add
pria = np.array([-3, -1, 0, 1, 3]) # array with both positive and negative values

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


#### Unary Operation

In [9]:
import numpy as np

a = np.array([-3, -1, 0, 1, 3]) # array with both positive and negative values

# Applying a unary operation: absolute value
print(np.absolute(a))

[3 1 0 1 3]


#### Binary Operation

In [ ]:
import numpy as np

# Two example arrays
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])

# Applying a binary operation: addition
res = np.add(a1, a2)
print(res)

[5 7 9]


#### Mathematical Functions

In [ ]:
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi]) 
print(np.sin(a))

# exponential values
b = np.array([0, 1, 2, 3])
print(np.exp(b))
print(np.sqrt(b))

# square root of array values
print (np.sqrt(a))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          2.71828183  7.3890561  20.08553692]
[0.         1.         1.41421356 1.73205081]
[0.         1.25331414 1.77245385]


## Sorting Arrays

In [14]:
import numpy as np

dtype = [('name', 'S10'), ('year', int), ('cgpa', float)]
vals  = [('Hrithik', 2009, 8.5),
         ('Ajay',    2008, 8.7),
         ('Pankaj',  2008, 7.9),
         ('Aakash',  2009, 9.0)]

a = np.array(vals, dtype=dtype)

print(np.sort(a, order='name'))
print(np.sort(a, order=['year', 'cgpa']))

[(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
[(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


#### Accessing the Array Index

In [3]:
import numpy as np
 
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

arr2 = arr[:2, ::2]  # first 2 rows and alternate columns(0 and 2)
print ("first 2 rows and alternate columns(0 and 2):\n", arr2)
 
arr3 = arr[[1, 1, 0, 3],          # row indices
                [3, 2, 1, 0]]     # column indices
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", arr3)

first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]


In [4]:
## Basic Array Operations

import numpy as np
 
a = np.array([[1, 2],
              [3, 4]])
 
b = np.array([[4, 3],
              [2, 1]])
               
print ("Adding 1 to every element:", a + 1)
print ("\nSubtracting 2 from each element:", b - 2)
print ("\nSum of all array elements: ", a.sum())
print ("\nArray sum:\n", a + b)

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]


#### Data Types in Numpy

In [5]:
import numpy as np
 
x = np.array([1, 2])  
print(x.dtype)         
 
x = np.array([1.0, 2.0]) 
print(x.dtype)  
 
x = np.array([1, 2], dtype = np.int64)   
print(x.dtype)

int64
float64
int64


In [ ]:
### Math Operations on DataType array
import numpy as np
 
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)

arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
Sum = np.add(arr1, arr2)
print(Sum)

Sum1 = np.sum(arr1)
print(Sum1)
 
Sqrt = np.sqrt(arr1)
print(Sqrt)

Trans_arr = arr1.T  # Transpose of the array
print(Trans_arr)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


### Attributes of NumPy Arrays

In [9]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.shape)  # shape of the array
print(arr.dtype)  # data type of the array elements
print(arr.ndim)   # number of dimensions
print(arr.size)   # total number of elements

(2, 3)
int64
2
6


### Matrix Multiplication

In [11]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(np.dot(a, b))

[[19 22]
 [43 50]]


In [4]:
####  Broadcasting
import numpy as np
arr = np.array([[1, 2], [3, 4]]) 

print(arr + 10)    # adds 10 to each element of the array

[[11 12]
 [13 14]]


#### Multi-Dimensional Array

In [12]:
import numpy as np

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1, 
                         list_2,
                         list_3])
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
