##### Attributes of ndarray

In [2]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)  
print("Dimensions:", arr.ndim)  
print("Size:", arr.size) 
print("Data type:", arr.dtype)  
print("Item size:", arr.itemsize)   # Size of each element in bytes
print("Total bytes:", arr.nbytes)   # Total bytes consumed by the array

Shape: (2, 3)
Dimensions: 2
Size: 6
Data type: int64
Item size: 8
Total bytes: 48


In [1]:
### Reshaping the array
import numpy as np 
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [2]:
## Flattening the array : convert multi-dimensional array into a 1D array
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = arr.flatten()
print(flattened_arr)

[1 2 3 4 5 6]
