In [1]:
import numpy as np
### Create array using numpy
## Create a 1D array
arr1 = np.array([1,2,3,4,5,6,])
print1 = print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [3]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)  # 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
arr2.shape

(2, 3)

In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [26]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
## Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print("Array : \n",arr)
print("Shape : ",arr.shape)
print("Size : ",arr.size)
print("Data type : ",arr.dtype)
print("Number of dimensions : ",arr.ndim)
print("Item size : ",arr.itemsize)

Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape :  (3, 3)
Size :  9
Data type :  int64
Number of dimensions :  2
Item size :  8


In [29]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10,11,12])

print("Addition : ",arr1 + arr2)
print("Subtraction : ",arr1 - arr2)
print("Multiplication : ",arr1 * arr2)
print("Division : ",arr1 / arr2)

Addition :  [ 8 10 12 14 16 18]
Subtraction :  [-6 -6 -6 -6 -6 -6]
Multiplication :  [ 7 16 27 40 55 72]
Division :  [0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [7]:
## Universal functions
arr = np.array([1,2,3,4,5])

print("Square root : ",np.sqrt(arr))
print("Exponential : ",np.exp(arr))
print("Sine : ",np.sin(arr))
print("Cosine : ",np.cos(arr))
print("tan : ",np.tan(arr))


Square root :  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential :  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sine :  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cosine :  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
tan :  [ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [58]:
## Indexing and slicing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n",arr)


Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:

print(arr[0][0])

1


In [ ]:
# slicing
# arr[row_start:row_end, col_start:col_end]      # row_end and col_end are exclusive

arr[1:3,2:4]

array([[ 7,  8],
       [11, 12]])

In [74]:
print(arr[0][2])
print(arr[0,2])

3
3


In [75]:
arr[1:] = 100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [8]:
data = np.array([1,2,3])

#mean
print("Mean : ",np.mean(data))
#median
print("Median : ",np.median(data))
#standard deviation
print("Standard Deviation : ",np.std(data))
#variance
print("Variance : ",np.var(data))

Mean :  2.0
Median :  2.0
Standard Deviation :  0.816496580927726
Variance :  0.6666666666666666


In [9]:
## Logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

In [78]:
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [79]:
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [83]:
data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])